
CREATE TABLE rol(
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	name VARCHAR(50) UNIQUE,
	PRIMARY KEY (id)
);

CREATE TABLE permissions(
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	name VARCHAR(100) UNIQUE,
	PRIMARY KEY (id)
);

CREATE TABLE device_type(
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	name VARCHAR(100) UNIQUE,
	PRIMARY KEY (id)
);

CREATE TABLE user(
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	name VARCHAR(150) NOT NULL,
	surname VARCHAR(150) NOT NULL,
	email VARCHAR(150) NOT NULL UNIQUE,
	rol_id INT UNSIGNED NOT NULL,
	PRIMARY KEY (id),
	FOREIGN KEY(rol_id) REFERENCES rol(id)
);

CREATE TABLE family(
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	surname VARCHAR(150) NOT NULL,
	main_user_id INT UNSIGNED NOT NULL,
	PRIMARY KEY (id),
	FOREIGN KEY(main_user_id) REFERENCES user(id)
);

CREATE TABLE device(
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	external_id INT UNSIGNED NOT NULL UNIQUE,
	device_type INT UNSIGNED NOT NULL,
	PRIMARY KEY (id),
	FOREIGN KEY(device_type) REFERENCES device(id)
);

CREATE TABLE user_permission_device(
	user_id INT UNSIGNED NOT NULL,
	permission_id INT UNSIGNED NOT NULL,
	device_id INT UNSIGNED NOT NULL,
	PRIMARY KEY (user_id, permission_id, device_id),
	FOREIGN KEY(user_id) REFERENCES user(id),
	FOREIGN KEY(permission_id) REFERENCES permissions(id),
	FOREIGN KEY(device_id) REFERENCES device(id)
);